version: "3"
services:
  earthquake-mqtt-fetcher-json-client:
    container_name: earthquake-mqtt-fetcher-json-client
    image: earthquake-mqtt-fetcher-json-client:v1.0.26
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /earthquake_mqtt_fetcher:/data
